version: 2.1
orbs:
  docker: circleci/docker@1.5.0
jobs:
  build_test: #Give ur job a name. 
    docker:  #where u want to run the job. called executor. it executes the code. 4 executors: docker, macos, machine (full blown linux or VM- where more horse power is required), windows 
      - image: circleci/python:3.9 
    steps: #actual commands thats going to run.
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install --user --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: ~/.local/bin/pytest
  build_push_docker_image:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Build app binary 
          command: |
            pip install --user --no-cache-dir -r requirements.txt          
            ~/.local/bin/pyinstaller -F hello_world.py
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          extra_build_args: "-t $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME"
          tag: 0.1.<< pipeline.number >>             
      - docker/push:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: "latest"
      - docker/push:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: "0.1.<< pipeline.number >>"
workflows:
  test_build_deploy:
    jobs:
      - build_test
      - build_push_docker_image:
          requires:
            - build_test
